#!/bin/bash

_run_python_code() {
    python3${pVer%.*} -c "$1"
}

_run_aliengit() {
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO="'$UPSTREAM_REPO'"
ACTIVE_BRANCH_NAME = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_start_bot () {
    local zippath
    zippath="alien.zip"
    echo "• Downloading Source Code . . ."
    wget -q $(UPSTREAM_REPO) -O "$zippath"
    echo "• Unpacking Source Code . . ."
    ALIENPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "• Successfuly Unpacking Source Code . . ."
    echo "• Cleaning . . ."
    rm -rf "$zippath"
    cd $ALIENPATH
    _run_aliengit
    chmod -R 755 bin
    echo "•   Starting Alien Userbot   •"
    python3 -m userbot
}

_start_bot
