#!/bin/bash

_run_python_code() {
    python3${pVer%.*} -c "$1"
}

_run() {
    $(_run_python_code '    
import os
import sys
import glob
import shutil
import zipfile

os.system("wget -q https://github.com/MxAboli/UserBot/archive/master.zip -O alien.zip")

z = zipfile.ZipFile("alien.zip", "r")
z.extractall("./")

for x in glob.glob("/app/*"):
    if not "UserBot-master" in x:
        if os.path.isfile(x):
            os.remove(x)
        else:
            shutil.rmtree(x)

for file in glob.glob("./UserBot-master/*"):
    if os.path.isdir(file):
        shutil.copytree(file, file.replace("UserBot-master/", ""))
    else:
        shutil.copy(file, file.replace("UserBot-master/", ""))

shutil.rmtree("./UserBot-master")
')
}

_start_bot () {
    python3 -m userbot
}

_run
_start_bot
