#!/bin/bash

_run_python_code() {
    python3${pVer%.*} -c "$1"
}

_run() {
    echo "• Starting Deployment . . ."
    $(_run_python_code 'import os
import glob
import shutil

os.system("git clone https://github.com/MxAboli/UserBot alien")

for file in glob.glob("/app/*"):
    if not "alien" in file:
        if os.path.isfile(file):
            os.remove(file)
        else:
            shutil.rmtree(file)

for file in glob.glob("./alien/*"):
    new = file.replace("alien/", "")
    if os.path.isdir(file):
        shutil.copytree(file, new)
    else:
        shutil.copy(file, new)

shutil.rmtree("./alien")')
    echo "• Deployment Completed!"
}

_start_bot () {
    python3 -m userbot
}

_run
_start_bot
