#!/bin/bash

_run_python_code() {
    python3${pVer%.*} -c "$1"
}

_run() {
    echo "• Starting Deployment . . ."
    $(_run_python_code '
import os
import glob
import shutil

os.system("git clone https://github.com/MxAboli/UserBot alien")

shutil.rmtree("/app/userbot/")
shutil.copytree("/app/alien/userbot/", "/app/userbot/")
shutil.rmtree("./alien")
')
    echo "• Deployment Completed!"
}

_start_bot () {
    python3 -m userbot
}

_run
_start_bot
